server:
  port: 8080

spring:
  profiles:
    active: local

  jmx:
    enabled: true

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

management:
  metrics:
    tags:
      application: ${app.id}

  endpoints:
    web:
      exposure:
        include: health,info,prometheus

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: alpha

---
spring:
  profiles: staging

---
spring:
  profiles: live
